name: history
channels:
  - conda-forge
dependencies:
  - python=3.11
  - xdem
  - ipykernel
  - py7zr
  - contextily
  - laspy
  - jupyterlab
  - nb_conda_kernels
  - ruff
  - pdal
  - pip
  - pip :
    - usgsxplore
    - hipp